config/routes.rb
Rails.application.routes.draw do

  root "sessions#home"

  get '/signup/employee' => 'employees#new'
  get '/signup/customer' => 'customers#new'

  get '/sessions/new' => 'sessions#new'
  post '/sessions' => 'sessions#create'

  get "logout" => 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#google' 
  #get '/auth/github/callback' => 'sessions#github'
  # always do custom routes before these resources route

  
  resources :customers do 
    resources :jobs, only: [:new, :create, :index]
  end
  
  resources :jobs do 
    resources :tasks, only: [:new, :create, :index]
  end
  
  resources :employees do 
    resources :jobs, only: [:new, :create, :index]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_secure_password
    
    validates :name, :email, presence: true
    validates :email, uniqueness: true

    has_many :jobs
    has_many :employees, through: :jobs 

end 
 

app/models/employee.rb
class Employee < ApplicationRecord 
    has_secure_password
    validates :first_name, :last_name, :email, :password, :password_confirmation, :specialty,  presence: true
    validates :email, uniqueness: true

    has_many :jobs 
    has_many :customers, through: :jobs
end  

app/models/job.rb
class Job < ApplicationRecord
    has_many :tasks
    has_many :comments
    belongs_to :customer
    belongs_to :employee, optional: true  

    validates :location, presence: true

    scope :completed, -> { where(completed: true)}

    def self.search(params)
        self.joins(:tasks).where(tasks: { name: "#{params}"})
    end

end
 

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :job
    validates :name, presence: true
    validates_inclusion_of :name, :in => ["Lawn Mowing", "Mulch", "Fertilizing", "Spring/Fall Clean Up", "Hedge Trimming"], 
                            message: " of task must be one of the following; Lawn Mowing, Mulch, Fertilizing, Spring/Fall Clean Up, Hedge Trimming."

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
helper_method :current_employee, :current_customer, :logged_in_as_customer?, :logged_in_as_employee?

    private 

        def current_employee
            @current_employee ||= Employee.find_by_id(session[:employee_id]) if session[:employee_id]
        end

        def current_customer
            @current_customer ||= Customer.find_by_id(session[:customer_id]) if session[:customer_id] 
        end

        def logged_in_as_customer?
            !!current_customer
        end

        def logged_in_as_employee?
            !!current_employee
        end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    before_action :require_login, only: [:index]

    def index
        if 
            params[:job_id] && @job = Job.find_by_id(params[:job_id])
            @customers = @job.customers.build 
        else
            @customers = Customer.all 
        end 

    end

    def new 
        @customer = Customer.new
    end

    def create 
        @customer = Customer.new(customer_params) 
        if @customer.save
            session[:customer_id] = @customer.id 
            redirect_to customer_path(@customer) #goes to show page
        else
            render "/customers/new"
        end
    end

    def show 
        @customer = Customer.find(params[:id])
        redirect_to '/' if !@customer 
    end

    private 

    def customer_params
        params.require(:customer).permit(:name, :email, :password, :password_confirmation)
    end

    def require_login 
        return head(:forbidden) unless session.include? :user_id
    end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :require_login, only: [:index]
    
    def index
        @employees = Employee.all
    end
 
    def new    
        @employee = Employee.new  
    end

    def create 
        @employee = Employee.new(employee_params)
        if @employee.save
            session[:employee_id] = @employee.id 
            redirect_to employee_path(@employee) #goes to show page
        else
            render "/employees/new"
        end
    end

    def show 
        @employee = Employee.find_by_id(params[:id])
        redirect_to '/' if !@employee 
    end

    private

    def employee_params
        params.require(:employee).permit(:first_name, :last_name, :email, :password, :password_confirmation, :specialty)
    end

    def require_login 
        return head(:forbidden) unless session.include? :user_id
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

    def index  
        if params[:customer_id] && @customer = Customer.find_by_id(params[:customer_id])
            @jobs = @customer.jobs

        else
            params[:employee_id] 
            @jobs = Job.all
        end
        if params[:q] && !params[:q].empty?
            @jobs = @jobs.search(params[:q])
        end
    end

    def show 
        @job = Job.find(params[:id])
        @task = @job.tasks.build
    end

    def new 
        @job = Job.new 
    end

    def create
        @job = current_customer.jobs.build(job_params)
         if @job.save
            redirect_to job_path(@job) #goes to show page
        else
            flash[:message] = "Location can not be blank."
            render "/jobs/new" 
        end
    end

    def edit
        if 
            session[:employee_id].present? 
            @job = Job.find_by(id: params[:id])
        else
            flash[:message] = "You're not authorized to make changes."
            render "/sessions/home"
        end
    end

    def update
        @job = Job.find_by(id: params[:id])
        @job.completed = params[:job][:completed]
        @job.employee_id = session[:employee_id]
        @job.update(job_params)
        redirect_to job_path(@job)
    end

    private

        def job_params
            params.require(:job).permit(:location, completed:[])
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: :create

    def new 
        
    end

    def create 
        if (params[:user][:email]) == "" || (params[:user][:password]) == ""
            
            flash[:message] = "Invalid email or password, please try again."
            render '/sessions/new'
            
        elsif user = Employee.find_by(email: params[:user][:email])
            
           if user && user.authenticate(params[:user][:password])
            session[:employee_id] = user.id
            redirect_to employee_path(user) 
           else
            flash[:message] = "Invalid email or password, please try again."
            render '/sessions/new'
           end
        elsif user = Customer.find_by(email: params[:user][:email])
            
            if user && user.authenticate(params[:user][:password])
            session[:customer_id] = user.id
        
            redirect_to customer_path(user)
            else 
                flash[:message] = "Invalid email or password, please try again."
            render '/sessions/new'
            end
        end
    end

    def google 
          @customer = Customer.find_or_create_by(provider: auth['provider'], uid: auth['uid']) do |c|
            c.name = auth['info']['name']
            c.email = auth['info']['email'] 
            c.password = SecureRandom.hex(10)
          end
        if @customer.valid?
            session[:customer_id] = @customer.id 
            redirect_to customer_path(@customer)
        else
            redirect_to "/"
        end
    end
        
    def destroy 
        session.destroy
        redirect_to root_path
    end

    private 

        def auth 
            request.env['omniauth.auth']
        end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController 

    def index 
        @tasks = Task.all 
    end

    def new 
        @task = Task.new 
    end

    def create
        @job = Job.find(params[:job_id])
        @task = @job.tasks.build(task_params)
        if @task.save
        redirect_to job_path(@job) #goes to show page
        else 
            render "jobs/show"
        end
    end

    def show 
        @task = Task.find(params[:id])
    end

    private 

    def task_params
        params.require(:task).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
    
end

app/views/customers/index.html.erb
<h1>All Customers</h1>

<ul>

<% @customers.each do |c| %>
    <li><%= c.name %></li>
    <% end %>
</ul>

app/views/customers/new.html.erb
<ul>    
<h1>Customer Sign Up</h1>
    <%= form_for(@customer) do |f| %>
        <% if @customer.errors.any? %>
            <div class="alert alert-danger">
             <% @customer.errors.full_messages.each do |message| %>
                 <div><%= message %></div>
                 <% end %>
                 </div>
             <% end %>

    <li><%= f.label :name %></li>
    <li><%= f.text_field :name, prompt: true %><br></li>
    <li><%= f.label :email %></li>
    <li><%= f.text_field :email %><br></li>

    <li><%= f.label :password %></li>
    <li><%= f.password_field :password %><br></li>

    <li><%= f.label :password_confirmation %></li>
    <li><%= f.password_field :password_confirmation %><br></li>

    <li><%= f.submit "Submit" %></li>
     <br>
    <% end %> 
    <li><%= button_to "Sign Up With Google", "/auth/google_oauth2" %> <br></li>
</ul>

app/views/customers/show.html.erb
<h1>Welcome</h1>

<ul>
<li>Name: <%= @customer.name %></li>
<li>Email: <%= @customer.email %></li>
</ul>

app/views/employees/index.html.erb
<h1>All Employees!!!</h1>

<ul>

<% @employees.each do |e| %>
    <li><%= e.first_name + " " + e.last_name %></li>
    <li><%= e.specialty %></li>
    <% end %>
</ul>

app/views/employees/new.html.erb
<h1>Employee Sign Up</h1>

<%= form_for(@employee) do |f| %>
    <% if @employee.errors.any? %>
        <div class="alert alert-danger">
        <% @employee.errors.full_messages.each do |message| %>
            <div><%= message %></div>
            <% end %>
            </div>
            <% end %>

    <ul>
        <li><%= f.label :first_name %></li>
        <li><%= f.text_field :first_name %></li>

        <li><%= f.label :last_name %></li>
        <li><%= f.text_field :last_name %></li>

        <li><%= f.label :email %></li>
        <li><%= f.text_field :email %></li>

        <li><%= f.label :password %></li>
        <li><%= f.password_field :password %></li>

        <li><%= f.label :password_confirmation %></li>
        <li><%= f.password_field :password_confirmation %></li>

        <li><%= f.label :specialty %></li>
        <li><%= f.text_field :specialty %></li>
        <br>
        <%= f.submit "Submit" %>
        <% end %>
    </ul>

app/views/employees/show.html.erb
<h1>Employee Info</h1>

    <ul>
        <li>Name: <%= @employee.first_name + " " + @employee.last_name %></li>
        <li>Email: <%= @employee.email %></li>
        <li>Specialty: <%= @employee.specialty %></li>
    </ul>

app/views/jobs/edit.html.erb
<h1>Edit A Job</h1>

<%= form_for(@job) do |f| %>

    <%= f.label :location %>
    <%= f.text_field :location %>
    <br>
    <br>
    <%= form_for @job do |f| %>
        <%= f.check_box :completed, :class => "toggle" %><%= label_tag 'completed', 'Completed' %>
    <br>
    <br>
    <%= f.submit "Submit" %>
    <% end %>
    <% end %>

app/views/jobs/index.html.erb
<h1>My Jobs</h1>

<%= form_tag("/jobs", method: 'get') do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
<% end %>
<br>

<section class="parent">
    <section class="child">
    <h2>Incomplete Jobs</h2>
    <ul class="index">
    <% @jobs.each do |j| %>
        <% if !j.completed %>
        <li><%= link_to j.location, "/jobs/#{j.id}" %></li>
        <% if session[:employee_id].present? %>
        <li><%= link_to "Edit", edit_job_path(j) %></li>
        <br>
        <% end %>
        <% end %>
        <% end %>
    </ul>
    </section>
    
    <section class="child">
        <h2>Complete Jobs</h2>
        <ul class="index">
            <% @jobs.each do |j| %>
            <% if j.completed %>
            <li><%= link_to j.location, "/jobs/#{j.id}" %></li>
            <% if session[:employee_id].present? %>
            <br>
            <% end %>
            <% end %>
            <% end %>
        </ul>

    </section>

    

    <section class="child">
        <% if !!current_employee %>
            <h2>Customers To Invoice</h2>
            <ul class="index">
                <% @jobs.each do |j| %>
                <% if j.completed && j.employee_id == current_employee.id %>
                <li><%= j.customer.name %></li>
                <% end %>
                <% end %>
            </ul>
        <% else !!current_customer %>
            <h2>Invoices</h2>
            <ul class="index">
                <% @jobs.each do |j| %>
                <% if j.completed && j.customer_id == current_customer.id %>
                <li><%= link_to j.location, "/jobs/#{j.id}" %></li>
                <% end %>
                <% end %>
                <% end %>
            </ul>
    </section>

</section>

app/views/jobs/new.html.erb
<h1>Create A New Job</h1>

<ul>
    <li><%= form_for(@job) do |f| %></li>
    <li><%= f.label :location %></li>
    <li><%= f.text_field :location %></li>
    <li><br></li>
    <li><%= f.submit "Submit" %></li>
    <li><% end %></li>
</ul>

    <% if @job.errors.any? %>
        <div class="alert alert-danger">
        <% @job.errors.full_messages.each do |message| %>
            <div><%= message %></div>
            <% end %>
            <% end %>

app/views/jobs/show.html.erb
<h1>Job</h1>

<ul>
    <li><%= @job.location %> </li>
    <li><% @job.tasks.each do |task| %></li>
    <li><%= task.name %> </li>
    <li><% end %></li>
    <li><% if @job.completed %></li>
    <li class="job">Job Complete</li>
    <li><% else session[:customer_id].present? && !@job.completed %></li>
    <li><%= form_for([@job, @task]) do |f| %></li>
    <li><%= f.text_field :name, :class => "new-todo" %></li>
    <li><%= f.submit %></li>
    <li><% end %></li>
    <li><% end %></li>
</ul>

<% if @task.errors.any? %>
    <div class="alert alert-danger">
    <% @task.errors.full_messages.each do |message| %>
    <div><%= message %></div>
    <% end %>
    <% end %>
    

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Landscaper</title>

    <link rel="preconnect" href="https://fonts.gstatic.com" />

    <link href="https://fonts.googleapis.com/css2?family=Lora&family=Noto+Sans+JP:wght@500&display=swap" rel="stylesheet"/>

    <%= stylesheet_link_tag "application.css" %>
  </head>

  <body>
    
    <div class="nav">
      <% if logged_in_as_customer? %>
        <%= link_to "Add a Job", new_job_path %> |
        <%= link_to "View My Jobs", "/customers/#{current_customer.id}/jobs" %> |
        <%= link_to "Logout", logout_path, method: "delete" %>
      | Logged In As: <%= current_customer.name %>
      <% elsif logged_in_as_employee? %>
        <%= link_to "View All Jobs", jobs_path %> |
        <%= link_to "Logout", logout_path, method: "delete" %>
      | Logged In As: <%= current_employee.first_name %>
      <% else %>
        <%= link_to "Customer Sign Up", "/customers/new" %> |
        <%= link_to "Employee Sign Up", "/employees/new" %> |
        <%= link_to "Log In", "/sessions/new" %>
      <% end %>
    </div>

    <%= yield %>
    
  </body>
</html>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>

<ul>

<% @tasks.each do |t| %>
    <%= t.name %><br>
    <% end %>
</ul>

<%= link_to "Create New Task", "/tasks/new" %> 

app/views/tasks/new.html.erb
<h1>Create A New Task</h1>

<%= form_for(@task) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit "Submit" %>
    <% end %>

app/views/tasks/show.html.erb
<h1>Task</h1>

<ul>
<li>Task: <%= @task.name %></li>
</ul>

<%= link_to "Create New Task", "/tasks/new" %> 